### ISSUE TITLE
Importing handles from ash?

### ISSUE THREAD

**Issue by cheako** [sjb3d/spark#2]
I'm attempting to setup imgui, but currently I'm using ash.  Can't I provide u64 as instance, physical_device, and device IDs to setup the vkr structs?

**Comment by cheako** [comment]
I found I could do it after making a few things public:
https://gitlab.com/cheako/ash-tray-rs/blob/af54afdda969dcc620732b37e27c07a8675ec10f/rebase-vkr.sh#L17

**Comment by sjb3d** [comment]
Apologies for the delayed response, I had not watched the repo, so have only just seen the issue.

I hadn't really considered interop, but I'm fine with adding some unsafe functions to make handles from raw values and making the load functions public, which I think should cover it?

**Comment by sjb3d** [comment]
Added Handle::from_raw and the load functions are now public
